INSERT INTO Users(Login, Password, Email, IsActive) VALUES('temp', 'temp', 'temp', 0);
INSERT INTO DictionaryLevelValues(DictionaryLevel) VALUES('A1');
INSERT INTO DictionaryLevelValues(DictionaryLevel) VALUES('A2');
INSERT INTO DictionaryLevelValues(DictionaryLevel) VALUES('B1');
INSERT INTO DictionaryLevelValues(DictionaryLevel) VALUES('B2');
INSERT INTO DictionaryLevelValues(DictionaryLevel) VALUES('C1');
INSERT INTO DictionaryLevelValues(DictionaryLevel) VALUES('C2');
INSERT INTO Dictionaries(DictionaryName, DictionaryLevelId, isDefaultDictionary, IsPublic, userId, DictionaryDescription) VALUES('Części ciała', 1 , 1, 1, 1, 'Części ciała z poziomu A1.');
INSERT INTO Dictionaries(DictionaryName, DictionaryLevelId, isDefaultDictionary, IsPublic, userId, DictionaryDescription) VALUES('Czynności', 1 ,1, 1, 1, 'Czynności z poziomu A1.');
INSERT INTO Dictionaries(DictionaryName, DictionaryLevelId, isDefaultDictionary, IsPublic, userId, DictionaryDescription) VALUES('Jedzenie i picie', 1 ,1, 1, 1, 'Jedzenie i picie z poziomu A1.');
INSERT INTO Dictionaries(DictionaryName, DictionaryLevelId, isDefaultDictionary, IsPublic, userId, DictionaryDescription) VALUES('Kolory',1,1, 1, 1, 'Kolory z poziomu A1.');
INSERT INTO Dictionaries(DictionaryName, DictionaryLevelId, isDefaultDictionary, IsPublic, userId, DictionaryDescription) VALUES('Miejsce zamieszkania',1,1, 1, 1, 'Miejsce zamieszkania z poziomu A1.');
INSERT INTO Dictionaries(DictionaryName, DictionaryLevelId, isDefaultDictionary, IsPublic, userId, DictionaryDescription) VALUES('Natura',1,1, 1, 1, 'Natura z poziomu A1.');
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('głowa','head',1);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('ucho','ear',1);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('oko','eye',1);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('nos','nose',1);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('usta','mouth',1);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('gardło','throat',1);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('ręka','arm',1);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('noga','leg',1);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('dłoń','hand',1);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('palec','finger',1);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('stopa','foot',1);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('plecy','back',1);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('klatka piersiowa','chest',1);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('kręgosłup','spine',1);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('jeść','eat',2);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('spać','sleep',2);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('patrzeć','look',2);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('dotykać','touch',2);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('uśmiechać się','smile',2);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('iść','walk',2);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('biec','run',2);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('pisać','write',2);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('pisać na klawiaturze','type',2);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('czytać','read',2);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('ćwiczyć','exercise',2);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('rysować','draw',2);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('mówić','speak',2);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('słuchać','listen',2);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('grać','play',2);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('śpiewać','sing',2);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('warzywa','vegetables',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('owoce','fruits',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('chleb','bread',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('mięso','meat',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('ryba','fish',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('ser','cheese',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('ryż','rice',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('jajko','egg',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('cukier','sugar',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('lody','ice cream',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('czekolada','chocolate',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('ciastko','biscuit',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('cukierek','candy',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('napój','drink',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('woda','water',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('mleko','milk',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('kawa','coffee',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('herbata','tea',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('sok','juice',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('napój gazowany','fizzy drink',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('piwo','beer',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('wino','wine',3);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('różowy','pink',4);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('czerwony','red',4);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('pomarańczowy','orange',4);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('żółty','yellow',4);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('zielony','green',4);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('niebieski','blue',4);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('fioletowy','purple',4);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('biały','white',4);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('czarny','black',4);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('brązowy','brown',4);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('szary','grey',4);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('beżowy','beige',4);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('ciemnoniebieski','dark blue',4);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('jasnoniebieski','light blue',4);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('brama','gate',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('drzwi wejściowe','front door',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('schody','stairs',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('balkon','balcony',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('salon','living room',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('okno','window',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('łazienka','bathroom',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('jadalnia','dining room',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('sypialnia','bedroom',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('kuchnia','kitchen',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('ściana','wall',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('podłoga','floor',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('dywan','carpet',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('sufit','ceiling',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('światło','light',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('włącznik','switch',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('gniazdko','socket',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('kaloryfer','radiator',5);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('roślina','plant',6);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('kwiat','flower',6);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('las','forest',6);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('drzewo','tree',6);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('krzak','bush',6);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('trawa','grass',6);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('góra','mountain',6);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('skała','rock',6);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('wyspa','island',6);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('morze','sea',6);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('rzeka','river',6);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('jezioro','lake',6);
INSERT INTO Words(wordPolish, WordTranslated, DictionaryId) VALUES('staw','pond',6);
